# Generated by Django 3.0.4 on 2020-06-04 13:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='Nom')),
                ('slug', models.SlugField(max_length=96, verbose_name='Adresse (slug)')),
                ('image', models.ImageField(upload_to='', verbose_name='Illustration')),
                ('description', models.TextField(verbose_name='Description')),
                ('publication_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('modification_date', models.DateTimeField(auto_now=True, null=True)),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Auteur')),
            ],
        ),
        migrations.CreateModel(
            name='Shelf',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='Nom')),
                ('slug', models.SlugField(max_length=96, verbose_name='Adresse (slug)')),
                ('description', models.TextField(verbose_name='Description')),
            ],
        ),
        migrations.CreateModel(
            name='Chapter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='Nom')),
                ('slug', models.SlugField(max_length=96, verbose_name='Adresse (slug)')),
                ('description', models.TextField(verbose_name='Description')),
                ('content', models.TextField(verbose_name='Contenu')),
                ('publication_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('modification_date', models.DateTimeField(auto_now=True, null=True)),
                ('book', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.Book', verbose_name='Livre')),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Auteur')),
            ],
        ),
        migrations.AddField(
            model_name='book',
            name='shelf',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.Shelf', verbose_name='Étagère'),
        ),
    ]
