# Generated by Django 3.0.4 on 2020-06-04 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20200604_1440'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='slug',
            field=models.SlugField(max_length=96, verbose_name='Adresse (slug)'),
        ),
    ]
